In [17]:
import pandas as pd
file_path = "Infosys.xlsx"
income = pd.read_excel(file_path, sheet_name="Income Statement")
cashflow = pd.read_excel(file_path, sheet_name="Cash Flow")
balance = pd.read_excel(file_path, sheet_name="Balance Sheet")

In [18]:
income.set_index(income.columns[0], inplace=True)
cashflow.set_index(cashflow.columns[0], inplace=True)
balance.set_index(balance.columns[0], inplace=True)
print("Income Statement:")
print(income.head())

print("\nCash Flow:")
print(cashflow.head())

Income Statement:
               2014-03-01 00:00:00  2015-03-01 00:00:00  2016-03-01 00:00:00  \
Unnamed: 0
Sales                     50133.00             53319.00             62441.00
Expenses                  36743.00             38436.00             45362.00
EBIT                      13390.00             14883.00             17079.00
OPM %                         0.27                 0.28                 0.27
Other Income               2664.00              3430.00              3120.00

               2017-03-01 00:00:00  2018-03-01 00:00:00  2019-03-01 00:00:00  \
Unnamed: 0
Sales                     68484.00             70522.00             82675.00
Expenses                  49880.00             51700.00             62505.00
EBIT                      18604.00             18822.00             20170.00
OPM %                         0.27                 0.27                 0.24
Other Income               3050.00              3311.00              2882.00

               2020-03-01 00:00:00  2021-03-01 00:00:00  2022-03-01 00:00:00  \
Unnamed: 0
Sales                     90791.00            100472.00            121641.00
Expenses                  68524.00             72583.00             90150.00
EBIT                      22267.00             27889.00             31491.00
OPM %                         0.25                 0.28                 0.26
Other Income               2803.00              2201.00              2295.00

               2023-03-01 00:00:00  2024-03-01 00:00:00  2025-03-01 00:00:00
Unnamed: 0
Sales                    146767.00            153670.00            162990.00
Expenses                 111637.00            117245.00            123754.00
EBIT                      35130.00             36425.00             39236.00
OPM %                         0.24                 0.24                 0.24
Other Income               2701.00              4711.00              3600.00

Cash Flow:
                                2014-03-01 00:00:00  2015-03-01 00:00:00  \
Unnamed: 0
Cash from Operating Activity                   9825                 8353
CapEx (Fixed Assets Purchased)                -2748                -2247
Cash from Investing Activity                  -2563                  999
Cash from Financing Activity                  -3144                -4935
Net Cash Flow                                  4118                 4417

                                2016-03-01 00:00:00  2017-03-01 00:00:00  \
Unnamed: 0
Cash from Operating Activity                  10028                11531
CapEx (Fixed Assets Purchased)                -2723                -2760
Cash from Investing Activity                   -885               -14664
Cash from Financing Activity                  -6813                -6939
Net Cash Flow                                  2330               -10072

                                2018-03-01 00:00:00  2019-03-01 00:00:00  \
Unnamed: 0
Cash from Operating Activity                  13218                14841
CapEx (Fixed Assets Purchased)                -1998                -2445
Cash from Investing Activity                   4533                 -632
Cash from Financing Activity                 -20505               -14512
Net Cash Flow                                 -2754                 -303

                                2020-03-01 00:00:00  2021-03-01 00:00:00  \
Unnamed: 0
Cash from Operating Activity                  17003                23224
CapEx (Fixed Assets Purchased)                -3307                -2107
Cash from Investing Activity                   -331                -7373
Cash from Financing Activity                 -17591                -9786
Net Cash Flow                                  -919                 6065

                                2022-03-01 00:00:00  2023-03-01 00:00:00  \
Unnamed: 0
Cash from Operating Activity                  23885                22467
CapEx (Fixed Assets Purchased)                -2161                -2579
Cash from Investing Activity                  -6485                -1071
Cash from Financing Activity                 -24642               -26695
Net Cash Flow                                 -7242                -5299

                                2024-03-01 00:00:00  2025-03-01 00:00:00
Unnamed: 0
Cash from Operating Activity                  25210                35694
CapEx (Fixed Assets Purchased)                -2201                -2237
Cash from Investing Activity                  -5093                -1864
Cash from Financing Activity                 -17504               -24161
Net Cash Flow                                  2613                 9669

In [19]:
income.index = income.index.str.strip()
cashflow.index = cashflow.index.str.strip()
balance.index = balance.index.str.strip()

In [20]:
revenue = income.loc["Sales"]
ebit = income.loc["EBIT"]
cfo = cashflow.loc["Cash from Operating Activity"]
capex = cashflow.loc["CapEx (Fixed Assets Purchased)"]
print("Revenue:")
print(revenue)
print("\nEBIT:")
print(ebit)
print("\nCFO:")
print(cfo)
print("\nCapEx:")
print(capex)

Revenue:
2014-03-01 00:00:00     50133.0
2015-03-01 00:00:00     53319.0
2016-03-01 00:00:00     62441.0
2017-03-01 00:00:00     68484.0
2018-03-01 00:00:00     70522.0
2019-03-01 00:00:00     82675.0
2020-03-01 00:00:00     90791.0
2021-03-01 00:00:00    100472.0
2022-03-01 00:00:00    121641.0
2023-03-01 00:00:00    146767.0
2024-03-01 00:00:00    153670.0
2025-03-01 00:00:00    162990.0
Name: Sales, dtype: float64

EBIT:
2014-03-01 00:00:00    13390.0
2015-03-01 00:00:00    14883.0
2016-03-01 00:00:00    17079.0
2017-03-01 00:00:00    18604.0
2018-03-01 00:00:00    18822.0
2019-03-01 00:00:00    20170.0
2020-03-01 00:00:00    22267.0
2021-03-01 00:00:00    27889.0
2022-03-01 00:00:00    31491.0
2023-03-01 00:00:00    35130.0
2024-03-01 00:00:00    36425.0
2025-03-01 00:00:00    39236.0
Name: EBIT, dtype: float64

CFO:
2014-03-01 00:00:00     9825
2015-03-01 00:00:00     8353
2016-03-01 00:00:00    10028
2017-03-01 00:00:00    11531
2018-03-01 00:00:00    13218
2019-03-01 00:00:00    14841
2020-03-01 00:00:00    17003
2021-03-01 00:00:00    23224
2022-03-01 00:00:00    23885
2023-03-01 00:00:00    22467
2024-03-01 00:00:00    25210
2025-03-01 00:00:00    35694
Name: Cash from Operating Activity, dtype: int64

CapEx:
2014-03-01 00:00:00   -2748
2015-03-01 00:00:00   -2247
2016-03-01 00:00:00   -2723
2017-03-01 00:00:00   -2760
2018-03-01 00:00:00   -1998
2019-03-01 00:00:00   -2445
2020-03-01 00:00:00   -3307
2021-03-01 00:00:00   -2107
2022-03-01 00:00:00   -2161
2023-03-01 00:00:00   -2579
2024-03-01 00:00:00   -2201
2025-03-01 00:00:00   -2237
Name: CapEx (Fixed Assets Purchased), dtype: int64

In [21]:
#calculating FCF
fcf = cfo + capex
print("Free Cash Flow:")
print(fcf)

Free Cash Flow:
2014-03-01 00:00:00     7077
2015-03-01 00:00:00     6106
2016-03-01 00:00:00     7305
2017-03-01 00:00:00     8771
2018-03-01 00:00:00    11220
2019-03-01 00:00:00    12396
2020-03-01 00:00:00    13696
2021-03-01 00:00:00    21117
2022-03-01 00:00:00    21724
2023-03-01 00:00:00    19888
2024-03-01 00:00:00    23009
2025-03-01 00:00:00    33457
dtype: int64

In [22]:
# Calculating year-on-year growth
growth = fcf.pct_change()
print("FCF Growth Rate:")
print(growth)

FCF Growth Rate:
2014-03-01 00:00:00         NaN
2015-03-01 00:00:00   -0.137205
2016-03-01 00:00:00    0.196364
2017-03-01 00:00:00    0.200684
2018-03-01 00:00:00    0.279216
2019-03-01 00:00:00    0.104813
2020-03-01 00:00:00    0.104873
2021-03-01 00:00:00    0.541837
2022-03-01 00:00:00    0.028745
2023-03-01 00:00:00   -0.084515
2024-03-01 00:00:00    0.156929
2025-03-01 00:00:00    0.454083
dtype: float64

In [23]:
filtered_growth = growth[(growth > -0.2) & (growth < 0.3)]
avg_growth = filtered_growth.mean()
print("Normalized Growth:", avg_growth)
years = 5
last_fcf = fcf.iloc[-1]
fcf_forecast = []
for i in range(1, years+1):
    future_fcf = last_fcf * (1 + avg_growth)**i
    fcf_forecast.append(future_fcf)
fcf_forecast = [float(x) for x in fcf_forecast]
print(fcf_forecast)

Normalized Growth: 0.09443369190467166
[36616.4680300546, 40074.29629064204, 43858.66003984907, 48000.395229403905, 52533.24976379992]

In [24]:
import yfinance as yf

# Use explicit date range
stock = yf.download("INFY.NS", start="2018-01-01", end="2026-01-01")
market = yf.download("^NSEI", start="2018-01-01", end="2026-01-01")

print(stock.head())
print(stock.tail())
print(stock.index.min())
print(stock.index.max())

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Ticker         INFY.NS     INFY.NS     INFY.NS     INFY.NS   INFY.NS
Date
2018-01-01  415.244202  419.643508  413.817916  416.911487   5431340
2018-01-02  413.697388  418.639117  411.005582  416.730733   6112248
2018-01-03  410.322601  414.460776  409.237831  413.215314   6846552
2018-01-04  407.952179  410.202053  405.621922  410.202053   8947614
2018-01-05  406.586151  412.371577  404.175561  407.911971  11025976
Price             Close         High          Low         Open   Volume
Ticker          INFY.NS      INFY.NS      INFY.NS      INFY.NS  INFY.NS
Date
2025-12-24  1663.400024  1667.599976  1652.500000  1661.000000  4271167
2025-12-26  1656.099976  1668.800049  1651.699951  1663.400024  2006491
2025-12-29  1644.699951  1673.099976  1637.099976  1658.000000  4062817
2025-12-30  1621.599976  1647.900024  1616.800049  1647.000000  9395937
2025-12-31  1615.400024  1628.599976  1609.199951  1621.000000  6538656
2018-01-01 00:00:00
2025-12-31 00:00:00

In [25]:
stock_close = stock['Close']
market_close = market['Close']

In [26]:
stock_returns = stock_close.pct_change()
market_returns = market_close.pct_change()

data = pd.concat([stock_returns, market_returns], axis=1).dropna()
data.columns = ['Stock', 'Market']

In [27]:
import numpy as np

cov = np.cov(data['Stock'], data['Market'])[0][1]
var = np.var(data['Market'])
beta = cov / var
print("Real Beta:", beta)

Real Beta: 0.8422505008475688

In [30]:
# Interest expense from Income Statement
interest = income.loc["Interest"].iloc[-1]

# Total debt from Balance Sheet
debt = balance.loc["Borrowings"].iloc[-1]

# Cost of Debt
cost_of_debt = interest / debt

print("Cost of Debt:", cost_of_debt)

Cost of Debt: 0.050565212106478664

In [33]:
# Cost of Equity
rf = 0.07
rm = 0.12

cost_of_equity = rf + beta * (rm - rf)

# Capital structure
equity = balance.loc["Equity Capital"] + balance.loc["Reserves"]
debt = balance.loc["Borrowings"]

equity_latest = equity.iloc[-1]
debt_latest = debt.iloc[-1]

# Tax rate
tax_rate = income.loc["Tax %"].iloc[-1] / 100

# Total value
total_value = equity_latest + debt_latest

# WACC
wacc = (equity_latest / total_value) * cost_of_equity + \
       (debt_latest / total_value) * cost_of_debt * (1 - tax_rate)

print("WACC:", wacc)

WACC: 0.10723428828401767

In [34]:
discounted_fcf = []

for i in range(len(fcf_forecast)):
    pv = fcf_forecast[i] / (1 + wacc)**(i+1)
    discounted_fcf.append(pv)

discounted_fcf = [float(x) for x in discounted_fcf]

print("Discounted FCF:")
print(discounted_fcf)

Discounted FCF:
[33070.20783000001, 32687.887315640786, 32309.986760673757, 31936.455066504157, 31567.241725281685]

In [35]:
g = 0.04  # long-term growth (4%)

terminal_value = fcf_forecast[-1] * (1 + g) / (wacc - g)

pv_terminal = terminal_value / (1 + wacc)**len(fcf_forecast)

print("Terminal Value:", terminal_value)
print("PV of Terminal Value:", pv_terminal)

Terminal Value: 812599.9567892973
PV of Terminal Value: 488291.4987604173

In [36]:
enterprise_value = sum(discounted_fcf) + pv_terminal

print("Enterprise Value:", enterprise_value)

Enterprise Value: 649863.2774585177

In [37]:
cash = balance.loc["Investments"].iloc[-1] + balance.loc["Other Assets"].iloc[-1]
debt = balance.loc["Borrowings"].iloc[-1]

equity_value = enterprise_value + cash - debt

print("Equity Value:", equity_value)

Equity Value: 757656.2774585177

In [38]:
shares = 2073   # Equity capital (₹ crore)

value_per_share = equity_value / shares

print("Intrinsic Value per Share:", value_per_share)

Intrinsic Value per Share: 365.4878328309299

In [39]:
wacc_range = [0.09, 0.10, 0.11, 0.12,0.13]
g_range = [0.03, 0.04, 0.05,0.06]

In [57]:
sensitivity_table = []

for w in wacc_range:
    row = []
    for g in g_range:
        
        # Terminal value
        tv = fcf_forecast[-1] * (1 + g) / (w - g)
        
        # PV of terminal value
        pv_tv = tv / (1 + w)**len(fcf_forecast)
        
        # Discounted FCF
        pv_fcf = sum([fcf_forecast[i] / (1 + w)**(i+1) for i in range(len(fcf_forecast))])
        
        # Enterprise value
        ev = pv_fcf + pv_tv
        
        row.append(ev)
    
    sensitivity_table.append(row)

In [58]:
import pandas as pd

sensitivity_df = pd.DataFrame(
    sensitivity_table,
    index=[f"{int(w*100)}%" for w in wacc_range],
    columns=[f"{int(g*100)}%" for g in g_range]
)

print(sensitivity_df)

                3%             4%            5%            6%
9%   755459.088761  879512.017267  1.065591e+06  1.375724e+06
10%  644728.048192  730158.801628  8.497619e+05  1.029166e+06
11%  561767.413126  623562.553826  7.059561e+05  8.213070e+05
12%  497316.771553  543685.979806  6.033035e+05  6.827936e+05
13%  445820.058086  481619.642426  5.263691e+05  5.839042e+05

In [59]:
formatted_df = sensitivity_df.copy()

for col in formatted_df.columns:
    formatted_df[col] = formatted_df[col].apply(lambda x: f"{x:,.0f}")

print(formatted_df)

          3%       4%         5%         6%
9%   755,459  879,512  1,065,591  1,375,724
10%  644,728  730,159    849,762  1,029,166
11%  561,767  623,563    705,956    821,307
12%  497,317  543,686    603,304    682,794
13%  445,820  481,620    526,369    583,904

In [60]:
sensitivity_df.index.name = "WACC (%)"
sensitivity_df.columns.name = "Terminal Growth Rate (%)"
styled_df = sensitivity_df.style \
    .format("{:,.0f}") \
    .background_gradient(cmap="RdYlGn") \
    .set_caption("DCF Sensitivity Analysis (Enterprise Value in ₹ Crore)") \
    .set_properties(**{'text-align': 'center'})

styled_df

In [61]:
scenarios = {
    "Bear": {"wacc": 0.12, "g": 0.03},
    "Base": {"wacc": 0.10, "g": 0.04},
    "Bull": {"wacc": 0.09, "g": 0.05}
}

In [51]:
scenario_results = {}

for name, vals in scenarios.items():
    w = vals["wacc"]
    g = vals["g"]

    # Terminal value
    tv = fcf_forecast[-1] * (1 + g) / (w - g)
    pv_tv = tv / (1 + w)**len(fcf_forecast)

    # Discounted FCF
    pv_fcf = sum([fcf_forecast[i] / (1 + w)**(i+1) for i in range(len(fcf_forecast))])

    # Enterprise Value
    ev = pv_fcf + pv_tv

    scenario_results[name] = ev

scenario_results

{'Bear': 497316.77155270404,
 'Base': 730158.8016275634,
 'Bull': 1065591.4100264048}

In [52]:
scenario_df = pd.DataFrame.from_dict(scenario_results, orient='index', columns=['Enterprise Value'])

scenario_df

      Enterprise Value
Bear      4.973168e+05
Base      7.301588e+05
Bull      1.065591e+06

In [53]:
scenario_df["Enterprise Value"] = scenario_df["Enterprise Value"].apply(lambda x: f"{x:,.0f}")

print(scenario_df)

     Enterprise Value
Bear          497,317
Base          730,159
Bull        1,065,591

In [54]:
scenario_df_numeric = pd.DataFrame.from_dict(scenario_results, orient='index', columns=['EV'])

scenario_df_numeric["Equity Value"] = scenario_df_numeric["EV"] + cash - debt
scenario_df_numeric["Value per Share"] = scenario_df_numeric["Equity Value"] / shares

scenario_df_numeric

                EV  Equity Value  Value per Share
Bear  4.973168e+05  6.051098e+05       291.900517
Base  7.301588e+05  8.379518e+05       404.221805
Bull  1.065591e+06  1.173384e+06       566.032036

In [55]:
final_df = pd.DataFrame.from_dict(scenario_results, orient='index', columns=['Enterprise Value'])

# Add Equity Value
final_df["Equity Value"] = final_df["Enterprise Value"] + cash - debt

# Add Value per Share
final_df["Value per Share"] = final_df["Equity Value"] / shares

def highlight_base(row):
    if row.name == 'Base':
        return ['background-color: yellow'] * len(row)
    return [''] * len(row)

styled_final = final_df.style \
    .set_caption("Scenario Valuation Summary (₹ Crore & Per Share)") \
    .background_gradient(cmap="RdYlGn", subset=["Enterprise Value", "Equity Value"]) \
    .apply(highlight_base, axis=1) \
    .format({
        "Enterprise Value": "{:,.0f}",
        "Equity Value": "{:,.0f}",
        "Value per Share": "{:,.0f}"
    }) \
    .set_properties(**{
        'text-align': 'center',
        'font-size': '12pt'
        
    }) \
    .set_table_styles([
    {'selector': 'th', 'props': [('border', '1px solid black')]},
    {'selector': 'td', 'props': [('border', '1px solid black')]}
])
styled_final

In [66]:
valuation_summary = pd.DataFrame({
    "Metric": ["Enterprise Value", "Equity Value", "Intrinsic Value per Share"],
    "Value": [
        enterprise_value,
        equity_value,
        value_per_share
    ]
})

valuation_summary["Value"] = valuation_summary["Value"].apply(lambda x: f"{x:,.2f}")

valuation_summary

                      Metric       Value
0           Enterprise Value  649,863.28
1               Equity Value  757,656.28
2  Intrinsic Value per Share      365.49

In [67]:
wacc_table = pd.DataFrame({
    "Metric": ["Beta", "Cost of Equity", "Cost of Debt", "WACC"],
    "Value": [
        beta,
        cost_of_equity,
        cost_of_debt,
        wacc
    ]
})
valuation_summary.reset_index(drop=True, inplace=True)
wacc_table["Value"] = wacc_table.apply(
    lambda row: f"{row['Value']:.2%}" if row["Metric"] != "Beta" else f"{row['Value']:.2f}",
    axis=1
)

wacc_table

           Metric   Value
0            Beta    0.84
1  Cost of Equity  11.21%
2    Cost of Debt   5.06%
3            WACC  10.72%

In [69]:
years = [f"Year {i}" for i in range(1, len(fcf_forecast)+1)]

fcf_table = pd.DataFrame({
    "Year": years,
    "Forecasted FCF": fcf_forecast
})
fcf_table["Forecasted FCF"] = fcf_table["Forecasted FCF"].apply(lambda x: f"{x:,.2f}")
fcf_table

     Year Forecasted FCF
0  Year 1      36,616.47
1  Year 2      40,074.30
2  Year 3      43,858.66
3  Year 4      48,000.40
4  Year 5      52,533.25

In [64]:
discounted_table = pd.DataFrame({
    "Year": years,
    "Discounted FCF": discounted_fcf
})

discounted_table["Discounted FCF"] = discounted_table["Discounted FCF"].apply(lambda x: f"{x:,.2f}")

discounted_table

     Year Discounted FCF
0  Year 1      33,070.21
1  Year 2      32,687.89
2  Year 3      32,309.99
3  Year 4      31,936.46
4  Year 5      31,567.24

In [ ]:
DCF Valuation of Infosys
1. Objective

The objective of this project is to estimate the intrinsic value of Infosys using the Discounted Cash Flow (DCF) method. 
The model helps determine whether the stock is overvalued or undervalued based on future cash flow projections.

2. Data Collection

Financial data for Infosys was collected from Screener and Yahoo Finance. 
The data includes income statement, cash flow statement, and balance sheet items required for valuation.

3. Financial Analysis

The company’s financial performance was analyzed using key metrics such as revenue, operating profit, and net profit. 
This helps in understanding historical growth trends and profitability.

4. Free Cash Flow Calculation

Free Cash Flow (FCF) was calculated using cash from operating activities and capital expenditure. 
FCF represents the cash available to investors after accounting for investments in fixed assets.

Formula used:
FCF = Cash Flow from Operations + Capital Expenditure

5. Forecasting

Future free cash flows were projected for a period of 5 years using historical growth trends.
Growth rates were normalized to remove extreme fluctuations and ensure realistic projections.

6. WACC Calculation

The Weighted Average Cost of Capital (WACC) was calculated to discount future cash flows.
Cost of equity was estimated using the Capital Asset Pricing Model (CAPM), and cost of debt was derived from financial statement data.

7. Key Assumptions

The valuation is based on the following assumptions:

Risk-free rate: 7%
Market return: 12%
Beta: Calculated using market data
Terminal growth rate: 3%–5%
Forecast period: 5 years
WACC: Approximately 10–11%

8. DCF Valuation

Projected free cash flows were discounted using WACC to estimate their present value. 
A terminal value was calculated using the Gordon Growth Model to capture value beyond the forecast period.

9. Sensitivity Analysis

Sensitivity analysis was performed to evaluate how changes in WACC and terminal growth rate impact the valuation.
This helps assess the robustness and reliability of the model.

10. Scenario Analysis

Three scenarios were considered:

Bear case: Conservative assumptions
Base case: Most realistic assumptions
Bull case: Optimistic assumptions

This provides a range of possible valuations under different conditions.

11. Conclusion

The DCF model estimates a fair value of approximately ₹404 per share under the base case. 
The valuation ranges from ₹292 to ₹566 across different scenarios, highlighting the sensitivity of valuation to key assumptions.

12. Limitations

The model has certain limitations. 
The valuation is highly sensitive to assumptions such as growth rate and discount rate.
External market conditions and qualitative factors are not fully captured in the model.